/* ═══════════════════════════════════════════════════════════════
   YSLEM MARKET — CATALOGUE SOURCE
   Single source of truth for the storefront and the price index.
   Both HTML pages are generated from this file by build.js.

   Record shape
   ------------
   i   id                      s   shop id
   b   brand key (logo/color)  n   product name
   k   kind: FA | KEY | GIFT | LINK | METHOD | TOOL | SERVICE
   dur duration label          mo  billable months (null = one-off / lifetime)
   p   price EUR               w   retail EUR (0 = no public retail)
   f   flag: hot | best | new  int configurator type
   D   full description override   d  extra description lines
   W   full warning override       w2 extra warning lines
   sp  extra specification pairs
   ═══════════════════════════════════════════════════════════════ */
(function (root) {

  var SHOPS = [
    { id: 'discord', name: 'Discord Shop',     icon: '💜', blurb: 'Nitro, boosts, aged accounts and server work.' },
    { id: 'ai',      name: 'AI Shop',          icon: '🤖', blurb: 'Chat, image and code assistants on paid tiers.' },
    { id: 'stream',  name: 'Streaming Shop',   icon: '🎬', blurb: 'Video and music subscriptions, monthly to lifetime.' },
    { id: 'vpn',     name: 'VPN Shop',         icon: '🔒', blurb: 'Shared and private VPN access, long terms.' },
    { id: 'gaming',  name: 'Gaming Shop',      icon: '🎮', blurb: 'Accounts, passes, currency and top-ups.' },
    { id: 'tools',   name: 'Tools Shop',       icon: '🛠',  blurb: 'Creative suites, office keys and study tools.' },
    { id: 'smm',     name: 'Social Shop',      icon: '📈', blurb: 'Followers, views and members, per 1000.' }
  ];

  /* Brand tint used behind logos and on shop headers. */
  var BRANDS = {
    discord: '#5865F2', telegram: '#26A5E4', tiktok: '#FF0050', instagram: '#E4405F',
    twitter: '#ffffff', twitch: '#9146FF', adobe: '#FF0000', duolingo: '#58CC02',
    roblox: '#E2231A', steam: '#66C0F4', openai: '#10a37f', claude: '#D97757',
    gemini: '#4285F4', netflix: '#E50914', spotify: '#1DB954', disney: '#0063e5',
    hbo: '#A020F0', crunchy: '#F47521', youtube: '#FF0000', prime: '#00A8E1',
    deezer: '#A238FF', nord: '#4687FF', express: '#DA3940', minecraft: '#62B47A',
    fortnite: '#8B5CF6', xbox: '#107C10', capcut: '#00D9E9', canva: '#00C4CC',
    perplexity: '#20808D', midjourney: '#B4A7FF', cursor: '#DADADA', copilot: '#8B949E',
    eleven: '#D6D6E7', grok: '#B4B4C8', notion: '#E8E8E8', runway: '#8FE388',
    leonardo: '#F5C542', apple: '#F0F0F5', tidal: '#00FFFF', paramount: '#0064FF',
    peacock: '#FFC940', iptv: '#7FD1B9', surfshark: '#1EBFBF', proton: '#6D4AFF',
    cyberghost: '#FFDD00', ipvanish: '#3BB54A', windscribe: '#4C9BE8',
    playstation: '#0070D1', ea: '#FF4747', valorant: '#FF4655', riot: '#EB0029',
    gta: '#79AC42', nintendo: '#E60012', office: '#D83B01', windows: '#0078D4',
    grammarly: '#15C39A', figma: '#F24E1E', envato: '#82B540', coursera: '#0056D2',
    scribd: '#1E7B85', jetbrains: '#FE315D', autodesk: '#0696D7', onepass: '#3B82F6',
    filmora: '#00C1CD', soundcloud: '#FF5500', kick: '#53FC18', facebook: '#1877F2'
  };

  /* ── copy templates by kind ─────────────────────────────────── */
  var DESC = {
    FA: ['Full access account, credentials sent after payment.', 'Checked before listing.', 'Delivered within a minute of confirmation.', 'Open a ticket if something does not work.'],
    KEY: ['Applied to an account, delivered as a login key.', 'Checked before listing.', 'Delivered within a minute of confirmation.', 'Replacement handled through a ticket.'],
    GIFT: ['Delivered as a gift link you claim yourself.', 'Nothing is shared, no login required.', 'Delivered within a minute of confirmation.', 'Open a ticket if the link fails.'],
    LINK: ['Delivered as an activation link for your own account.', 'Nothing is shared, no login required.', 'Delivered within a minute of confirmation.', 'Open a ticket if the link fails.'],
    METHOD: ['Step by step method, delivered as text.', 'Written for the current version of the platform.', 'Delivered after payment confirmation.', 'Open a ticket if a step is unclear.'],
    TOOL: ['Delivered as a ready to run tool with instructions.', 'No installation is done for you.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
    SERVICE: ['Ordered against a public profile or link.', 'No password or login required.', 'Started after payment confirmation.', 'Open a ticket if delivery stalls.']
  };
  var WARN = {
    FA: ['Is Full Access, revokes are possible.', 'Do not change the password, email or recovery options.', 'Warranty is void once the credentials are modified.'],
    KEY: ['Account must have no active plan of the same type.', 'Cancel any running trial before redeeming.', 'Never change the password on a shared account.'],
    GIFT: ['Claimed on your own account, no token login.', 'Record a screen video while claiming for warranty.', 'No replacement during a provider-wide revoke wave.'],
    LINK: ['The link works once, follow the steps exactly.', 'Account must have no active plan of the same type.', 'No replacement once the link has been opened.'],
    METHOD: ['The provider can patch the method at any time.', 'Lifetime refers to the method, not the outcome.', 'No replacement once the method is delivered.'],
    TOOL: ['Automating a user account breaks most terms of service.', 'Your account can be terminated for using it.', 'No replacement if your account is banned.'],
    SERVICE: ['Delivery is bot traffic, drops are expected.', 'The platform can purge it at any time.', 'Target must stay public for the whole delivery window.']
  };
  var TYPEN = { FA: 'Full Access', KEY: 'Login key', GIFT: 'Gift link', LINK: 'Activation link', METHOD: 'Method', TOOL: 'Tool', SERVICE: 'SMM service' };
  var SUPPORT = { FA: '7 days', KEY: 'Open ticket', GIFT: '15 days', LINK: '30 days', METHOD: 'Ticket only', TOOL: 'Ticket only', SERVICE: '48 hours' };

  function mk(o) {
    var desc = o.D || DESC[o.k].concat(o.d || []);
    var warn = o.W || WARN[o.k].concat(o.w2 || []);
    var sp = { Type: TYPEN[o.k], Duration: o.dur, Delivery: o.del || 'Instant', Support: o.sup || SUPPORT[o.k] };
    if (o.sp) { for (var key in o.sp) sp[key] = o.sp[key]; }
    return {
      id: o.i, shop: o.s, brand: o.b, name: o.n, kind: o.k, dur: o.dur,
      months: o.mo === undefined ? null : o.mo,
      price: o.p, retail: o.w || 0, flag: o.f || null,
      int: o.int || 'basic', smm: o.smm || null,
      opts: o.opts || null,
      desc: desc, warn: warn, sp: sp
    };
  }

  var RAW = [

    /* ════════ DISCORD SHOP ════════ */
    { i: 1, s: 'discord', b: 'discord', n: 'Nitro Boost', k: 'GIFT', dur: '1 month', mo: 1, p: 2.30, w: 9.99, f: 'hot', int: 'nitro',
      D: ['Delivered as a gift link.', 'Full Nitro with 2 server boosts included.', 'Checked before listing.', 'Suitable for personal use and reselling.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Claimed on your own account, no token login.', 'Record a screen video while claiming for warranty.', 'Do not stack more than 2 Nitro credits per account.', 'No replacement during a Discord mass revoke wave.'] },
    { i: 36, s: 'discord', b: 'discord', n: 'Nitro Boost 3 Months', k: 'GIFT', dur: '3 months', mo: 3, p: 6.49, w: 29.97, int: 'nitro',
      d: ['Full Nitro with 2 boosts, three billing cycles.', 'Cheaper per month than the single month link.'] },
    { i: 37, s: 'discord', b: 'discord', n: 'Nitro Boost 1 Year', k: 'GIFT', dur: '12 months', mo: 12, p: 22.99, w: 119.88, f: 'best', int: 'nitro',
      d: ['A full year of Nitro with 2 boosts.', 'Best price per month in the Discord shop.'],
      w2: ['One year links are limited, stock runs out fast.'] },
    { i: 3, s: 'discord', b: 'discord', n: 'Nitro Basic', k: 'GIFT', dur: '1 month', mo: 1, p: 0.79, w: 2.99, int: 'nitro',
      D: ['Delivered as a gift link.', 'Custom emoji in every server.', '50MB file uploads unlocked.', 'Nitro badge on your profile.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Account must not have had Nitro in 12 months.', 'Server boosts are not included in this tier.', 'Record the claim process for warranty coverage.'] },
    { i: 38, s: 'discord', b: 'discord', n: 'Nitro Basic 1 Year', k: 'GIFT', dur: '12 months', mo: 12, p: 7.49, w: 35.88, int: 'nitro',
      d: ['Twelve months of Basic on one link.', 'No boosts at this tier.'] },
    { i: 39, s: 'discord', b: 'discord', n: '2x Server Boosts', k: 'SERVICE', dur: '1 month', mo: 1, p: 0.79, w: 9.99, int: 'boost',
      D: ['Two boosts applied by real Nitro accounts.', 'Applied within 30 minutes.', 'Useful to top a server up to the next level.', 'Open a ticket if a boost drops.'],
      W: ['Send a permanent server invite in the ticket.', 'Invite must have no expiry and no member limit.', 'Replacement window is one month.'] },
    { i: 40, s: 'discord', b: 'discord', n: '4x Server Boosts', k: 'SERVICE', dur: '1 month', mo: 1, p: 1.29, w: 15.99, int: 'boost',
      D: ['Four boosts applied by real Nitro accounts.', 'Applied within 30 minutes.', 'Open a ticket if a boost drops.'],
      W: ['Send a permanent server invite in the ticket.', 'Replacement window is one month.'] },
    { i: 41, s: 'discord', b: 'discord', n: '8x Server Boosts', k: 'SERVICE', dur: '1 month', mo: 1, p: 1.99, w: 31.99, int: 'boost',
      D: ['Eight boosts, enough to hold Level 2.', 'Applied within 30 minutes.', 'Open a ticket if a boost drops.'],
      W: ['Send a permanent server invite in the ticket.', 'Replacement window is one month.'] },
    { i: 2, s: 'discord', b: 'discord', n: '14x Server Boosts', k: 'SERVICE', dur: '1 month', mo: 1, p: 2.99, w: 54.99, f: 'best', int: 'boost',
      D: ['Targets Level 3 on your server.', '14 boosts applied by real Nitro accounts.', 'Checked before listing.', 'Suitable for personal use and reselling.', 'Applied within 30 minutes.', 'Open a ticket if a boost drops.'],
      W: ['Send a permanent server invite in the ticket.', 'Invite must have no expiry and no member limit.', 'Applied the same way as organic boosting.', 'Replacement window is one month.'] },
    { i: 42, s: 'discord', b: 'discord', n: '30x Server Boosts', k: 'SERVICE', dur: '1 month', mo: 1, p: 5.49, w: 119.99, int: 'boost',
      D: ['Thirty boosts, Level 3 with a wide margin.', 'Applied within an hour.', 'Open a ticket if a boost drops.'],
      W: ['Send a permanent server invite in the ticket.', 'Large orders are applied in waves.', 'Replacement window is one month.'] },
    { i: 43, s: 'discord', b: 'discord', n: '14x Boosts 3 Months', k: 'SERVICE', dur: '3 months', mo: 3, p: 7.99, w: 164.97, int: 'boost',
      D: ['Level 3 held for three months.', 'Dropped boosts are refilled during the term.', 'Applied within 30 minutes.'],
      W: ['Send a permanent server invite in the ticket.', 'Refills are manual, open a ticket when you see a drop.'] },
    { i: 4, s: 'discord', b: 'discord', n: 'Aged Account 2016-2020', k: 'FA', dur: 'Permanent', p: 2.49, f: 'new', int: 'aged',
      D: ['Credentials delivered on purchase.', 'Created between 2016 and 2020.', 'Email and phone already verified.', 'Full access, change everything freely.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, credentials included.', 'Change password and email immediately.', 'Warranty void once credentials are modified.', 'Specify preferred creation year in the ticket.'],
      sp: { Age: '2016-2020', Verified: 'Email + Phone' }, sup: '24 hours' },
    { i: 44, s: 'discord', b: 'discord', n: 'Aged Account 2015', k: 'FA', dur: 'Permanent', p: 4.99, int: 'aged',
      d: ['One of the oldest tiers still in stock.', 'Email and phone verified.'],
      w2: ['Stock is thin, delivery can take a few hours.'], sp: { Age: '2015', Verified: 'Email + Phone' }, sup: '24 hours' },
    { i: 45, s: 'discord', b: 'discord', n: 'Verified Token', k: 'FA', dur: 'Permanent', p: 0.35, int: 'aged',
      d: ['Mail-verified account delivered as a token.', 'Used for bots, farms and automation.'],
      w2: ['Token logins are detected and banned regularly.', 'Sold as-is, no replacement after delivery.'], sp: { Format: 'Token', Verified: 'Email' }, sup: 'None' },
    { i: 30, s: 'discord', b: 'discord', n: 'Profile Decoration', k: 'METHOD', dur: 'Lifetime', p: 1.53, f: 'new', int: 'method',
      D: ['Step by step method, delivered as text.', 'Unlocks decorations from the Discord shop.', 'Displayed with your own avatar.', 'Works on the official Discord app.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Requires a VPN and a payment method.', 'Discord can patch the method at any time.', 'Lifetime refers to the method, not the outcome.', 'No replacement once the method is delivered.'],
      sp: { Format: 'Text guide' } },
    { i: 49, s: 'discord', b: 'discord', n: 'Animated Avatar Method', k: 'METHOD', dur: 'Lifetime', p: 0.99, int: 'method',
      d: ['Sets a GIF avatar without an active Nitro plan.', 'Written for the desktop client.'] },
    { i: 31, s: 'discord', b: 'discord', n: 'Server Cloner', k: 'TOOL', dur: 'Lifetime', p: 0.99, int: 'method',
      D: ['Copies channels, roles and permissions.', 'Delivered as a ready to run tool.', 'Works on servers you have access to.', 'Includes usage instructions.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Using self-bots breaks Discord terms of service.', 'Your account can be terminated.', 'No replacement if your account is banned.'],
      sp: { Format: 'Script' } },
    { i: 46, s: 'discord', b: 'discord', n: 'Server Setup', k: 'SERVICE', dur: 'One-off', p: 4.99, int: 'method',
      D: ['A full server built for you: channels, roles, permissions.', 'Icons, banner and category layout included.', 'Delivered within 24 hours.', 'One round of changes included.'],
      W: ['You keep ownership, no admin role is retained.', 'Send your theme and rules in the ticket.'], sp: { Format: 'Done for you' }, del: 'Under 24 h', sup: '7 days' },
    { i: 47, s: 'discord', b: 'discord', n: 'Custom Bot', k: 'SERVICE', dur: 'One-off', p: 7.99, int: 'method',
      D: ['A bot written for your server: moderation, tickets, levels.', 'Source code delivered with the bot.', 'Hosting instructions included.', 'Delivered within 48 hours.'],
      W: ['Hosting is not included in the price.', 'Scope is agreed in the ticket before work starts.'], sp: { Format: 'Source + setup' }, del: 'Under 48 h', sup: '14 days' },

    /* ════════ AI SHOP ════════ */
    { i: 5, s: 'ai', b: 'openai', n: 'ChatGPT Plus', k: 'FA', dur: '1 month', mo: 1, p: 2.99, w: 19.99, f: 'hot', int: 'ai',
      D: ['Subscription product.', 'Unlimited GPT-5 access.', 'Checked before listing.', 'Suitable for personal use and reselling.', 'Advanced Data Analysis and DALL-E included.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, revokes are possible.', 'Do not change the password or email.', 'Works on most devices and regions.', 'Use a maximum of 2 devices at once.'] },
    { i: 50, s: 'ai', b: 'openai', n: 'ChatGPT Plus 3 Months', k: 'FA', dur: '3 months', mo: 3, p: 7.99, w: 59.97, int: 'ai',
      d: ['Three billing cycles on one account.', 'Cheaper per month than the single month.'] },
    { i: 51, s: 'ai', b: 'openai', n: 'ChatGPT Pro', k: 'FA', dur: '1 month', mo: 1, p: 14.99, w: 200.00, f: 'new', int: 'ai',
      d: ['Pro tier with the reasoning models unlocked.', 'Highest usage ceiling OpenAI sells.'],
      w2: ['Private account, never shared, but still resold access.'] },
    { i: 6, s: 'ai', b: 'claude', n: 'Claude Pro', k: 'FA', dur: '1 month', mo: 1, p: 7.99, w: 20.00, f: 'best', int: 'ai',
      D: ['Subscription product.', 'All Claude models unlocked including Opus.', 'Claude Code included.', '5x usage limits versus free tier.', 'Checked before listing.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, revokes are possible.', 'Do not change account settings or email.', 'Use a stable connection, avoid IP hopping.', 'Works on most devices and regions.'] },
    { i: 52, s: 'ai', b: 'claude', n: 'Claude Max', k: 'FA', dur: '1 month', mo: 1, p: 19.99, w: 100.00, int: 'ai',
      d: ['Max tier, the widest usage window on Claude.', 'Claude Code with the higher limits.'],
      w2: ['Heavy use on a shared account trips rate limits for everyone.'] },
    { i: 7, s: 'ai', b: 'gemini', n: 'Gemini Pro', k: 'LINK', dur: '18 months', mo: 18, p: 2.49, w: 19.99, int: 'link',
      D: ['Delivered as an activation link.', '18 months on your own Google account.', '2TB Google One storage included.', 'Gemini in Gmail, Docs and Sheets.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Applied to your account, nothing shared.', 'Account must have no active Google One plan.', 'The link works once, follow instructions exactly.'] },
    { i: 53, s: 'ai', b: 'perplexity', n: 'Perplexity Pro', k: 'LINK', dur: '12 months', mo: 12, p: 1.99, w: 200.00, f: 'best', int: 'link',
      d: ['Applied to your own Perplexity account.', 'Pro search, file uploads and model choice.'],
      w2: ['Account must be new or never subscribed.'] },
    { i: 54, s: 'ai', b: 'midjourney', n: 'Midjourney Standard', k: 'FA', dur: '1 month', mo: 1, p: 3.49, w: 30.00, int: 'ai',
      d: ['Standard plan with fast generation hours.', 'Used through the Midjourney site or Discord.'],
      w2: ['Your prompts and images are visible to other users of the account.'] },
    { i: 55, s: 'ai', b: 'cursor', n: 'Cursor Pro', k: 'FA', dur: '1 month', mo: 1, p: 3.99, w: 20.00, int: 'ai',
      d: ['Pro request quota inside the Cursor editor.', 'Frontier models on agent mode.'],
      w2: ['Quota is shared, heavy use exhausts it early.'] },
    { i: 56, s: 'ai', b: 'copilot', n: 'GitHub Copilot', k: 'FA', dur: '12 months', mo: 12, p: 2.99, w: 100.00, int: 'ai',
      d: ['Copilot in your editor and on github.com.', 'A full year on one account.'],
      w2: ['Do not push private repositories from the account.'] },
    { i: 57, s: 'ai', b: 'eleven', n: 'ElevenLabs Creator', k: 'FA', dur: '1 month', mo: 1, p: 2.49, w: 22.00, int: 'ai',
      d: ['Creator tier character quota for voice generation.', 'Voice cloning and dubbing included.'],
      w2: ['Quota is shared across everyone on the account.'] },
    { i: 58, s: 'ai', b: 'grok', n: 'Grok Premium+', k: 'FA', dur: '1 month', mo: 1, p: 3.99, w: 40.00, int: 'ai',
      d: ['Premium+ on X with the widest Grok limits.', 'Image generation included.'],
      w2: ['Do not post from the account, it is shared.'] },
    { i: 59, s: 'ai', b: 'notion', n: 'Notion AI', k: 'LINK', dur: '12 months', mo: 12, p: 2.49, w: 96.00, int: 'link',
      d: ['AI added to your own Notion workspace.', 'Writing, summaries and database autofill.'] },
    { i: 60, s: 'ai', b: 'runway', n: 'Runway Standard', k: 'FA', dur: '1 month', mo: 1, p: 2.99, w: 15.00, int: 'ai',
      d: ['Standard credits for video generation.', 'Gen video models and the editing tools.'],
      w2: ['Credits are shared, they can be spent before you log in.'] },
    { i: 61, s: 'ai', b: 'leonardo', n: 'Leonardo AI', k: 'FA', dur: '1 month', mo: 1, p: 1.99, w: 12.00, int: 'ai',
      d: ['Daily token allowance for image generation.', 'Private generation mode enabled.'] },

    /* ════════ STREAMING SHOP ════════ */
    { i: 8, s: 'stream', b: 'netflix', n: 'Netflix 4K', k: 'KEY', dur: 'Lifetime', p: 0.99, w: 17.99, f: 'hot', int: 'stream',
      opts: [['Standard', 0.00], ['Premium 4K', 0.30]],
      D: ['Subscription product.', 'Premium 4K Ultra HD plan.', 'Checked before listing.', 'Private profile assigned to you.', 'Replacement handled through a ticket.', 'Open a ticket if something does not work.'],
      W: ['Use only your assigned profile.', 'Never change the password or plan settings.', 'Do not add or remove profiles.', 'Works on most devices and regions.'],
      sp: { Plan: 'Premium 4K' } },
    { i: 62, s: 'stream', b: 'netflix', n: 'Netflix Private 1 Month', k: 'FA', dur: '1 month', mo: 1, p: 2.49, w: 17.99, int: 'stream',
      opts: [['Standard HD', 0.00], ['Premium 4K', 0.60]],
      d: ['A profile nobody else uses for one month.', 'Four screens, 4K where available.'] },
    { i: 63, s: 'stream', b: 'netflix', n: 'Netflix 1 Year', k: 'KEY', dur: '12 months', mo: 12, p: 4.99, w: 215.88, f: 'best', int: 'stream',
      opts: [['Standard HD', 0.00], ['Premium 4K', 1.00]],
      d: ['Twelve months on a shared Premium plan.', 'Replacements during the term are handled by ticket.'],
      w2: ['Long terms see more account rotations than monthly plans.'] },
    { i: 9, s: 'stream', b: 'spotify', n: 'Spotify Premium', k: 'KEY', dur: 'Lifetime', p: 1.49, w: 11.99, f: 'hot', int: 'ownacct',
      D: ['Subscription product.', 'Applied on your own account.', 'Keep all playlists and history.', 'Ad-free with offline downloads.', 'Replacement handled through a ticket.', 'Open a ticket if something does not work.'],
      W: ['Account must have no active Premium plan.', 'Cancel any running trial before redeeming.', 'Send your Spotify email in the ticket.'],
      sp: { Plan: 'Premium' } },
    { i: 64, s: 'stream', b: 'spotify', n: 'Spotify 3 Months', k: 'KEY', dur: '3 months', mo: 3, p: 2.49, w: 35.97, int: 'ownacct',
      d: ['Applied to your own account for three months.', 'Playlists and history are untouched.'] },
    { i: 65, s: 'stream', b: 'spotify', n: 'Spotify 12 Months', k: 'KEY', dur: '12 months', mo: 12, p: 4.99, w: 143.88, int: 'ownacct',
      d: ['A full year on your own account.', 'Best price per month for music here.'] },
    { i: 10, s: 'stream', b: 'disney', n: 'Disney Plus', k: 'FA', dur: 'Lifetime', p: 0.49, w: 8.99, f: 'best', int: 'stream',
      opts: [['Disney only', 0.00], ['Disney + Hulu', 0.25], ['Disney + Hulu + ESPN', 0.55]],
      D: ['Subscription product.', '4K streaming on up to 4 devices.', 'Checked before listing.', 'Hulu and ESPN+ bundle available.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, credentials included.', 'Do not change the password.', 'Create your own profile, do not use existing ones.', 'Works on most devices and regions.'],
      sp: { Plan: 'Premium 4K' } },
    { i: 66, s: 'stream', b: 'disney', n: 'Disney Plus 1 Year', k: 'FA', dur: '12 months', mo: 12, p: 2.49, w: 107.88, int: 'stream',
      opts: [['Disney only', 0.00], ['Disney + Hulu', 0.60]],
      d: ['Twelve months of Premium 4K.', 'Replacements during the term go through tickets.'] },
    { i: 11, s: 'stream', b: 'hbo', n: 'HBO Max', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 9.99, int: 'stream',
      opts: [['Standard', 0.00], ['4K Ultimate', 0.25]],
      D: ['Subscription product.', 'Complete HBO catalogue and Originals.', 'Checked before listing.', 'HD and 4K titles available.', 'Replacement handled through a ticket.', 'Open a ticket if something does not work.'],
      W: ['Never change the account password or email.', 'Use one profile only.', 'Do not exceed the device limit of the plan.'],
      sp: { Plan: 'Premium' } },
    { i: 12, s: 'stream', b: 'crunchy', n: 'Crunchyroll', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 6.99, int: 'stream',
      opts: [['Fan', 0.00], ['Mega Fan', 0.15]],
      D: ['Subscription product.', 'Mega Fan tier membership.', 'Unlimited anime with zero ads.', 'Same-day simulcast releases.', 'Replacement handled through a ticket.', 'Open a ticket if something does not work.'],
      W: ['Do not modify the account settings.', 'Warranty is void if the password is changed.', 'Report issues within 24 hours for fast replacement.'],
      sp: { Plan: 'Mega Fan' } },
    { i: 67, s: 'stream', b: 'crunchy', n: 'Crunchyroll 1 Year', k: 'KEY', dur: '12 months', mo: 12, p: 1.99, w: 83.88, int: 'stream',
      opts: [['Fan', 0.00], ['Mega Fan', 0.40]],
      d: ['Twelve months of ad-free anime.', 'Simulcasts the day they air.'] },
    { i: 13, s: 'stream', b: 'youtube', n: 'YouTube Premium', k: 'FA', dur: '1 month', mo: 1, p: 0.99, w: 13.99, int: 'ai',
      D: ['Subscription product.', 'Zero advertisements anywhere.', 'YouTube Music Premium included.', 'Background and offline playback.', 'Checked before listing.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, credentials included.', 'Do not enable 2FA or change recovery email.', 'Sign in on a maximum of two devices.', 'Works on most devices and regions.'] },
    { i: 68, s: 'stream', b: 'youtube', n: 'YouTube Premium 1 Year', k: 'LINK', dur: '12 months', mo: 12, p: 4.49, w: 167.88, f: 'best', int: 'link',
      d: ['Applied to your own Google account.', 'YouTube Music Premium included for the year.'],
      w2: ['Account must have no active Premium or trial.'] },
    { i: 14, s: 'stream', b: 'prime', n: 'Prime Video', k: 'KEY', dur: '1 month', mo: 1, p: 0.79, w: 6.99, int: 'stream',
      opts: [['1 month', 0.00], ['6 months', 1.00]],
      D: ['Subscription product.', 'Full Prime Video catalogue.', 'Amazon Originals included.', 'HD and 4K where available.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Prime Video only, no shipping benefits.', 'Do not change the password.', 'Do not add payment methods to the account.'], sup: '14 days' },
    { i: 69, s: 'stream', b: 'prime', n: 'Prime Video 1 Year', k: 'KEY', dur: '12 months', mo: 12, p: 2.99, w: 83.88, int: 'stream',
      d: ['Twelve months of Prime Video only.', 'Amazon Originals included.'],
      w2: ['No delivery or shipping benefits are attached.'] },
    { i: 15, s: 'stream', b: 'deezer', n: 'Deezer Premium', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 11.99, int: 'stream',
      opts: [['Premium', 0.00], ['HiFi', 0.20]],
      D: ['Subscription product.', '120M+ track library.', 'HiFi lossless audio quality.', 'Unlimited offline downloads.', 'Replacement handled through a ticket.', 'Open a ticket if something does not work.'],
      W: ['Do not change the account password.', 'Request replacement via ticket, do not recover.', 'Works on most devices and regions.'],
      sp: { Plan: 'Premium HiFi' } },
    { i: 70, s: 'stream', b: 'apple', n: 'Apple Music', k: 'KEY', dur: '3 months', mo: 3, p: 1.49, w: 32.97, int: 'ownacct',
      d: ['Redeemed on your own Apple ID.', 'Lossless and spatial audio included.'],
      w2: ['Apple ID must have no active Music plan or trial.'] },
    { i: 71, s: 'stream', b: 'tidal', n: 'Tidal HiFi', k: 'KEY', dur: 'Lifetime', p: 0.79, w: 10.99, int: 'stream',
      d: ['HiFi tier with lossless streaming.', 'Offline downloads enabled.'] },
    { i: 72, s: 'stream', b: 'paramount', n: 'Paramount Plus', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 7.99, int: 'stream',
      d: ['Full Paramount+ catalogue with Showtime titles.', 'HD streaming.'] },
    { i: 73, s: 'stream', b: 'peacock', n: 'Peacock Premium', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 7.99, int: 'stream',
      d: ['Premium tier with the full library.', 'Live sport where the region allows it.'],
      w2: ['Availability is limited outside the United States.'] },
    { i: 74, s: 'stream', b: 'iptv', n: 'IPTV 20K Channels', k: 'KEY', dur: '12 months', mo: 12, p: 9.99, w: 120.00, f: 'new', int: 'platform',
      d: ['20 000+ live channels and a VOD library.', 'Works on Smart TV, Android, Firestick and VLC.', 'One connection per subscription.'],
      w2: ['Streams go down without warning and come back on their own.', 'Some countries block the servers, a VPN may be required.'],
      sp: { Connections: '1 device' }, sup: '30 days' },

    /* ════════ VPN SHOP ════════ */
    { i: 16, s: 'vpn', b: 'nord', n: 'NordVPN', k: 'FA', dur: 'Lifetime', p: 1.99, w: 12.99, f: 'best', int: 'vpn',
      D: ['Subscription product.', '6000+ servers in 110 countries.', 'Strict no-logs policy.', 'Threat Protection included.', 'Checked before listing.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, credentials included.', 'Do not change the account email.', 'Account may be shared, slots can be full.', 'Retry after a few minutes if connection fails.'], sup: 'Open ticket' },
    { i: 75, s: 'vpn', b: 'nord', n: 'NordVPN Private 1 Year', k: 'FA', dur: '12 months', mo: 12, p: 3.99, w: 155.88, int: 'vpn',
      d: ['A private account, no sharing, for twelve months.', 'Six simultaneous devices.'] },
    { i: 17, s: 'vpn', b: 'express', n: 'ExpressVPN', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 12.99, f: 'hot', int: 'vpn',
      D: ['Subscription product.', 'Global server network.', 'Lightway fast protocol.', 'iOS and Android support.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Mobile devices only, no desktop activation.', 'Install the app before redeeming the key.', 'Works in most regions.'],
      sp: { Platform: 'iOS / Android' }, sup: 'Open ticket' },
    { i: 76, s: 'vpn', b: 'surfshark', n: 'Surfshark', k: 'FA', dur: 'Lifetime', p: 0.79, w: 12.95, int: 'vpn',
      d: ['Unlimited devices on one account.', 'CleanWeb ad blocking included.'] },
    { i: 77, s: 'vpn', b: 'proton', n: 'ProtonVPN Plus', k: 'FA', dur: 'Lifetime', p: 0.99, w: 9.99, int: 'vpn',
      d: ['Plus tier with Secure Core routing.', 'Ten devices per account.'] },
    { i: 78, s: 'vpn', b: 'proton', n: 'Proton Unlimited', k: 'FA', dur: '12 months', mo: 12, p: 1.99, w: 155.88, int: 'vpn',
      d: ['VPN, Mail, Drive and Pass on one account.', '500GB of encrypted storage.'],
      w2: ['Do not store anything private on a shared account.'] },
    { i: 79, s: 'vpn', b: 'cyberghost', n: 'CyberGhost', k: 'FA', dur: 'Lifetime', p: 0.69, w: 11.99, int: 'vpn',
      d: ['Streaming-optimised servers by country.', 'Seven devices per account.'] },
    { i: 80, s: 'vpn', b: 'ipvanish', n: 'IPVanish', k: 'FA', dur: 'Lifetime', p: 0.59, w: 12.99, int: 'vpn',
      d: ['Unlimited devices, no connection cap.', 'Works on Firestick and Android TV.'] },
    { i: 81, s: 'vpn', b: 'windscribe', n: 'Windscribe Pro', k: 'FA', dur: 'Lifetime', p: 0.49, w: 9.00, int: 'vpn',
      d: ['Unlimited data on the Pro tier.', 'Port forwarding and ad blocking.'] },

    /* ════════ GAMING SHOP ════════ */
    { i: 18, s: 'gaming', b: 'minecraft', n: 'Minecraft', k: 'FA', dur: 'Permanent', p: 1.49, w: 23.99, f: 'new', int: 'game',
      opts: [['Java + Bedrock', 0.00], ['Java only', -0.30]],
      D: ['Account delivered on purchase.', 'Java and Bedrock editions included.', 'Email fully changeable.', 'Username change available.', 'Checked before listing.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, ownership transfers to you.', 'Change email and password within the first hour.', 'Enable 2FA once the email is yours.', 'Warranty covers login failure on delivery only.'],
      sp: { Edition: 'Java + Bedrock' }, sup: '30 days' },
    { i: 82, s: 'gaming', b: 'minecraft', n: 'Minecraft Alt', k: 'FA', dur: 'Permanent', p: 0.49, int: 'game',
      opts: [['Java only', 0.00]],
      d: ['A cheap secondary account for servers.', 'No email access included.'],
      w2: ['Without email access the account cannot be secured.', 'Sold as-is, no replacement after delivery.'], sp: { Edition: 'Java' }, sup: 'None' },
    { i: 19, s: 'gaming', b: 'fortnite', n: 'Fortnite Account', k: 'FA', dur: 'Permanent', p: 0.99, f: 'hot', int: 'fortnite',
      D: ['Account delivered on purchase.', '1000+ skins on the account.', 'V-Bucks balance included.', 'Rare and OG cosmetics possible.', 'Full email access provided.', 'Open a ticket if something does not work.'],
      W: ['Accounts are randomly assigned from stock.', 'Specific skins cannot be requested.', 'Change email and password immediately.', 'Test the login before confirming receipt.'],
      sp: { Skins: '1000+' }, sup: '24 hours' },
    { i: 20, s: 'gaming', b: 'xbox', n: 'Xbox Game Pass 12M', k: 'KEY', dur: '12 months', mo: 12, p: 4.99, w: 59.99, f: 'best', int: 'region',
      D: ['Subscription product.', '100+ games available day one.', 'EA Play membership included.', 'Cloud gaming on any device.', 'Console and PC access.', 'Open a ticket if something does not work.'],
      W: ['Account must have no active Game Pass plan.', 'Region restrictions may apply.', 'Mention your country in the ticket.'],
      sp: { Tier: 'Ultimate' }, sup: '30 days' },
    { i: 83, s: 'gaming', b: 'xbox', n: 'Xbox Game Pass 1M', k: 'KEY', dur: '1 month', mo: 1, p: 0.99, w: 14.99, int: 'region',
      d: ['One month of Game Pass Ultimate.', 'Cloud gaming and EA Play included.'],
      w2: ['Account must have no active Game Pass plan.'] },
    { i: 84, s: 'gaming', b: 'playstation', n: 'PS Plus Deluxe 12M', k: 'KEY', dur: '12 months', mo: 12, p: 6.99, w: 151.99, int: 'region',
      d: ['Deluxe tier: online play plus the game catalogue.', 'Classics library included.'],
      w2: ['Region-locked, the key must match your account country.'] },
    { i: 85, s: 'gaming', b: 'ea', n: 'EA Play 12 Months', k: 'KEY', dur: '12 months', mo: 12, p: 2.49, w: 39.99, int: 'region',
      d: ['A year of the EA catalogue on PC or console.', 'Ten-hour trials on new releases.'] },
    { i: 34, s: 'gaming', b: 'roblox', n: 'Robux Top-Up', k: 'SERVICE', dur: 'Per 1000', p: 2.99, w: 9.99, f: 'hot', int: 'robux',
      D: ['Robux delivered to your own account.', 'No password or login required.', 'Delivered through the gamepass method.', 'Works on any Roblox account.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['You must create a gamepass for delivery.', 'Roblox takes a 30 percent cut on transfers.', 'Delivery can take up to 5 days due to pending.'],
      sp: { Unit: 'Per 1000' }, del: 'Up to 5 days', sup: '7 days' },
    { i: 86, s: 'gaming', b: 'roblox', n: 'Roblox Premium', k: 'KEY', dur: '1 month', mo: 1, p: 1.49, w: 4.99, int: 'ownacct',
      d: ['Premium 450 applied to your own account.', 'Monthly Robux stipend and trading unlocked.'] },
    { i: 35, s: 'gaming', b: 'steam', n: 'Steam Account', k: 'FA', dur: 'Permanent', p: 0.49, int: 'game',
      opts: [['4+ games', 0.00], ['10+ games', 0.80], ['With GTA V', 2.50]],
      D: ['Full access Steam account with games.', 'Random library, 4 or more titles.', 'Email access included.', 'Change all credentials freely.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Games are random, specific titles cannot be requested.', 'Change the email and password immediately.', 'Family sharing may be locked on some accounts.'],
      sp: { Library: '4+ games' }, sup: '24 hours' },
    { i: 87, s: 'gaming', b: 'steam', n: 'Steam Random Key', k: 'KEY', dur: 'Permanent', p: 0.29, int: 'game',
      opts: [['Random', 0.00], ['Premium pool', 1.20]],
      d: ['One random Steam key, activated on your own account.', 'Region free unless stated in the ticket.'],
      w2: ['The title is random and cannot be exchanged.'], sup: 'None' },
    { i: 88, s: 'gaming', b: 'gta', n: 'GTA V Account', k: 'FA', dur: 'Permanent', p: 1.99, w: 29.99, int: 'game',
      opts: [['Base account', 0.00], ['Modded money', 1.50]],
      d: ['Rockstar account with GTA V unlocked.', 'Email access included.'],
      w2: ['Modded balances can trigger a Rockstar ban wave.'] },
    { i: 89, s: 'gaming', b: 'valorant', n: 'Valorant Account', k: 'FA', dur: 'Permanent', p: 2.99, int: 'region',
      d: ['Ranked-ready account with agents unlocked.', 'Region chosen at order time.'],
      w2: ['Riot bans accounts that change region or are shared.'] },
    { i: 90, s: 'gaming', b: 'riot', n: 'Riot Points 1000', k: 'SERVICE', dur: 'Per 1000', p: 4.49, w: 9.99, int: 'region',
      d: ['Points added to your own Riot account.', 'Works on League and Valorant wallets.'],
      w2: ['Region must be stated in the ticket, top-ups are region locked.'], del: 'Under 24 h', sup: '7 days' },
    { i: 91, s: 'gaming', b: 'nintendo', n: 'Nintendo eShop 10€', k: 'KEY', dur: 'One-off', p: 6.99, w: 10.00, int: 'region',
      d: ['A 10 EUR eShop credit code.', 'Redeemed on your own Nintendo account.'],
      w2: ['Codes are region locked to the European eShop.'] },

    /* ════════ TOOLS SHOP ════════ */
    { i: 32, s: 'tools', b: 'adobe', n: 'Adobe Creative Cloud', k: 'FA', dur: '12 months', mo: 12, p: 4.99, w: 59.99, f: 'best', int: 'ai',
      D: ['Full access account with all Adobe apps.', 'Photoshop, Premiere, Illustrator, After Effects.', '100GB cloud storage included.', 'Works on desktop and mobile.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, revokes are possible.', 'Do not change the account email or password.', 'Sign in on a maximum of two devices.'], sup: '30 days' },
    { i: 92, s: 'tools', b: 'adobe', n: 'Adobe CC 1 Month', k: 'FA', dur: '1 month', mo: 1, p: 1.49, w: 59.99, int: 'ai',
      d: ['All Adobe apps for a single month.', 'Good for one project without a year commitment.'] },
    { i: 22, s: 'tools', b: 'canva', n: 'Canva Pro', k: 'FA', dur: '3 years', mo: 36, p: 2.99, w: 119.99, f: 'best', int: 'ai',
      D: ['Subscription product.', 'Unlimited premium templates.', 'Brand Kit and Magic Resize.', 'Background remover tool.', '100GB cloud storage.', 'Open a ticket if something does not work.'],
      W: ['Is Full Access, credentials included.', 'Do not change the account email.', 'Do not invite other members to the team.', 'Create your own folder to keep work separate.'], sup: '30 days' },
    { i: 21, s: 'tools', b: 'capcut', n: 'CapCut Pro', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 7.99, int: 'platform',
      D: ['Delivered as an activation key.', 'All premium effects unlocked.', 'No watermark on exports.', '4K export quality enabled.', 'Replacement handled through a ticket.', 'Open a ticket if something does not work.'],
      W: ['Works on web and desktop versions.', 'Mobile activation varies by region.', 'Mention your platform in the ticket.'] },
    { i: 93, s: 'tools', b: 'filmora', n: 'Filmora Pro', k: 'KEY', dur: 'Lifetime', p: 0.99, w: 49.99, int: 'platform',
      d: ['Watermark-free exports on desktop.', 'Effect and audio libraries unlocked.'] },
    { i: 33, s: 'tools', b: 'duolingo', n: 'Duolingo Super', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 6.99, int: 'stream',
      opts: [['Super', 0.00], ['Super Family', 0.50]],
      D: ['Delivered as an activation key.', 'Removes all advertisements.', 'Unlimited hearts and practice.', 'All languages unlocked.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Do not change the account password.', 'Progress on a shared account is visible to others.', 'Replacement handled through a ticket.'] },
    { i: 94, s: 'tools', b: 'office', n: 'Office 365 Lifetime', k: 'FA', dur: 'Lifetime', p: 1.99, w: 99.00, f: 'hot', int: 'ai',
      d: ['Word, Excel, PowerPoint and Outlook on five devices.', '1TB of OneDrive storage.'],
      w2: ['Microsoft deactivates resold family slots without warning.'] },
    { i: 95, s: 'tools', b: 'windows', n: 'Windows 11 Pro Key', k: 'KEY', dur: 'Permanent', p: 0.99, w: 199.00, int: 'platform',
      d: ['Retail activation key for one machine.', 'Activates a fresh install or an upgrade.'],
      w2: ['Keys can deactivate after a major hardware change.'], sup: '30 days' },
    { i: 96, s: 'tools', b: 'grammarly', n: 'Grammarly Premium', k: 'FA', dur: '12 months', mo: 12, p: 1.49, w: 144.00, int: 'ai',
      d: ['Premium checks in the browser and desktop app.', 'Tone and clarity rewrites included.'] },
    { i: 97, s: 'tools', b: 'notion', n: 'Notion Plus', k: 'LINK', dur: '12 months', mo: 12, p: 1.49, w: 96.00, int: 'link',
      d: ['Plus plan applied to your own workspace.', 'Unlimited blocks and file uploads.'] },
    { i: 98, s: 'tools', b: 'figma', n: 'Figma Professional', k: 'FA', dur: '12 months', mo: 12, p: 1.99, w: 144.00, int: 'ai',
      d: ['Professional seat with unlimited files.', 'Dev mode and shared libraries.'],
      w2: ['Do not remove other seats from the team.'] },
    { i: 99, s: 'tools', b: 'envato', n: 'Envato Elements', k: 'FA', dur: '1 month', mo: 1, p: 1.49, w: 16.50, int: 'ai',
      d: ['Unlimited downloads: templates, fonts, stock, music.', 'Licences are issued in the account name.'],
      w2: ['Commercial licences belong to the account holder, not to you.'] },
    { i: 100, s: 'tools', b: 'coursera', n: 'Coursera Plus', k: 'FA', dur: '12 months', mo: 12, p: 2.99, w: 399.00, int: 'ai',
      d: ['Access to 7000+ courses and certificates.', 'A year on one account.'],
      w2: ['Certificates carry the account holder name, not yours.'] },
    { i: 101, s: 'tools', b: 'scribd', n: 'Everand / Scribd', k: 'KEY', dur: 'Lifetime', p: 0.49, w: 11.99, int: 'stream',
      d: ['Unlimited books, audiobooks and documents.', 'Offline reading enabled.'] },
    { i: 102, s: 'tools', b: 'jetbrains', n: 'JetBrains All Products', k: 'FA', dur: '12 months', mo: 12, p: 3.99, w: 289.00, int: 'ai',
      d: ['Every JetBrains IDE on one licence.', 'A full year, activated in the IDE.'],
      w2: ['Licences are revoked when JetBrains audits the seat.'] },
    { i: 103, s: 'tools', b: 'autodesk', n: 'Autodesk 1 Year', k: 'FA', dur: '12 months', mo: 12, p: 2.99, w: 235.00, int: 'ai',
      d: ['AutoCAD, Fusion and Maya on one account.', 'Desktop activation.'] },
    { i: 104, s: 'tools', b: 'onepass', n: '1Password Families', k: 'FA', dur: '12 months', mo: 12, p: 0.99, w: 59.88, int: 'ai',
      d: ['A family slot with your own private vault.', 'Apps on desktop, mobile and browser.'],
      w2: ['The account owner can see membership and revoke your slot.', 'Never store real banking credentials in a shared plan.'] },

    /* ════════ SOCIAL SHOP ════════ */
    { i: 23, s: 'smm', b: 'discord', n: 'Discord Members', k: 'SERVICE', dur: 'Per 1000', p: 0.90, f: 'hot', int: 'smm',
      smm: { unit: 'members', min: 100, max: 20000, step: 100, rate: 0.9, field: 'Server invite link', ph: 'discord.gg/yourserver' },
      D: ['Delivered as online or offline members.', 'Drip-feed available to look organic.', 'Members join within a few hours.', 'Suitable for growing new servers.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Members are bots, they do not chat.', 'Discord can purge them at any time.', 'Do not order more than 2x your real member count.', 'Server must have a permanent invite link.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 6 h' },
    { i: 105, s: 'smm', b: 'discord', n: 'Discord Online Members', k: 'SERVICE', dur: 'Per 1000', p: 1.60, int: 'smm',
      smm: { unit: 'members', min: 100, max: 10000, step: 100, rate: 1.6, field: 'Server invite link', ph: 'discord.gg/yourserver' },
      d: ['Members that keep an online status in the sidebar.', 'Held for 30 days.'],
      w2: ['They never speak, an empty chat still reads as empty.'], sp: { Unit: 'Per 1000' }, del: 'Under 12 h' },
    { i: 24, s: 'smm', b: 'telegram', n: 'Telegram Members', k: 'SERVICE', dur: 'Per 1000', p: 1.20, int: 'smm',
      smm: { unit: 'members', min: 100, max: 20000, step: 100, rate: 1.2, field: 'Channel link', ph: 't.me/yourchannel' },
      D: ['Real-looking accounts added to your channel.', 'Drip-feed delivery to avoid detection.', 'Works on public channels and groups.', 'No admin access required.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Telegram may remove inactive members over time.', 'Channel must be public during delivery.', 'Refill is not automatic, open a ticket.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 12 h' },
    { i: 106, s: 'smm', b: 'telegram', n: 'Telegram Post Views', k: 'SERVICE', dur: 'Per 1000', p: 0.15, int: 'smm',
      smm: { unit: 'views', min: 1000, max: 200000, step: 1000, rate: 0.15, field: 'Post link', ph: 't.me/channel/42' },
      d: ['Views added to the last posts of a channel.', 'Delivered within an hour.'], sp: { Unit: 'Per 1000' }, del: 'Under 1 h' },
    { i: 25, s: 'smm', b: 'tiktok', n: 'TikTok Followers', k: 'SERVICE', dur: 'Per 1000', p: 0.60, f: 'best', int: 'smm',
      smm: { unit: 'followers', min: 100, max: 50000, step: 100, rate: 0.6, field: 'TikTok username', ph: '@yourhandle' },
      D: ['Followers added to your public profile.', 'Drip-feed over several hours.', 'No password or login required.', 'Works on any public account.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Drop rate varies, refills are not guaranteed.', 'Account must be public during delivery.', 'Do not change your username mid-delivery.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 24 h' },
    { i: 107, s: 'smm', b: 'tiktok', n: 'TikTok Likes', k: 'SERVICE', dur: 'Per 1000', p: 0.35, int: 'smm',
      smm: { unit: 'likes', min: 100, max: 50000, step: 100, rate: 0.35, field: 'Video link', ph: 'tiktok.com/@you/video/...' },
      d: ['Likes added to a single video.', 'Delivered within a few hours.'], sp: { Unit: 'Per 1000' }, del: 'Under 6 h' },
    { i: 108, s: 'smm', b: 'tiktok', n: 'TikTok Views', k: 'SERVICE', dur: 'Per 1000', p: 0.08, int: 'smm',
      smm: { unit: 'views', min: 1000, max: 500000, step: 1000, rate: 0.08, field: 'Video link', ph: 'tiktok.com/@you/video/...' },
      d: ['Views pushed to one video.', 'Cheapest social service in the shop.'], sp: { Unit: 'Per 1000' }, del: 'Under 3 h' },
    { i: 26, s: 'smm', b: 'instagram', n: 'Instagram Followers', k: 'SERVICE', dur: 'Per 1000', p: 0.80, int: 'smm',
      smm: { unit: 'followers', min: 100, max: 50000, step: 100, rate: 0.8, field: 'Instagram username', ph: '@yourhandle' },
      D: ['Followers added to your public profile.', 'Gradual delivery to look natural.', 'No password or login required.', 'Works on personal and business accounts.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Instagram purges bot accounts regularly.', 'Profile must be public during delivery.', 'Drops are common, refills are not guaranteed.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 24 h' },
    { i: 109, s: 'smm', b: 'instagram', n: 'Instagram Likes', k: 'SERVICE', dur: 'Per 1000', p: 0.45, int: 'smm',
      smm: { unit: 'likes', min: 100, max: 50000, step: 100, rate: 0.45, field: 'Post link', ph: 'instagram.com/p/...' },
      d: ['Likes added to one post or reel.', 'Delivered within a few hours.'], sp: { Unit: 'Per 1000' }, del: 'Under 6 h' },
    { i: 110, s: 'smm', b: 'instagram', n: 'Instagram Reel Views', k: 'SERVICE', dur: 'Per 1000', p: 0.10, int: 'smm',
      smm: { unit: 'views', min: 1000, max: 500000, step: 1000, rate: 0.10, field: 'Reel link', ph: 'instagram.com/reel/...' },
      d: ['Views added to a single reel.', 'Starts within the hour.'], sp: { Unit: 'Per 1000' }, del: 'Under 3 h' },
    { i: 27, s: 'smm', b: 'youtube', n: 'YouTube Views', k: 'SERVICE', dur: 'Per 1000', p: 0.40, int: 'smm',
      smm: { unit: 'views', min: 1000, max: 200000, step: 1000, rate: 0.4, field: 'Video link', ph: 'youtube.com/watch?v=...' },
      D: ['Views delivered to any public video.', 'Retention varies between 30 and 60 percent.', 'Delivered gradually over several hours.', 'No channel access required.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['YouTube audits views and may remove them.', 'Monetized channels are at higher risk.', 'Video must stay public and unlisted-free.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 48 h' },
    { i: 111, s: 'smm', b: 'youtube', n: 'YouTube Subscribers', k: 'SERVICE', dur: 'Per 1000', p: 4.50, int: 'smm',
      smm: { unit: 'subscribers', min: 100, max: 10000, step: 100, rate: 4.5, field: 'Channel link', ph: 'youtube.com/@yourchannel' },
      d: ['Subscribers added to a public channel.', 'Delivered slowly across several days.'],
      w2: ['Bought subscribers do not count toward monetisation.', 'A purge can take the whole batch back at once.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 5 days' },
    { i: 112, s: 'smm', b: 'youtube', n: 'YouTube Watch Hours', k: 'SERVICE', dur: 'Per 1000 h', p: 39.00, int: 'smm',
      smm: { unit: 'hours', min: 100, max: 4000, step: 100, rate: 39.0, field: 'Channel link', ph: 'youtube.com/@yourchannel' },
      d: ['Watch hours accumulated on long-form videos.', 'Delivered over one to two weeks.'],
      w2: ['YouTube reviews watch time before monetisation and can reject it.', 'This is the highest-risk service in the shop.'],
      sp: { Unit: 'Per 1000 hours' }, del: 'Up to 14 days' },
    { i: 28, s: 'smm', b: 'twitter', n: 'X Followers', k: 'SERVICE', dur: 'Per 1000', p: 0.70, int: 'smm',
      smm: { unit: 'followers', min: 100, max: 50000, step: 100, rate: 0.7, field: 'X username', ph: '@yourhandle' },
      D: ['Followers added to your public X profile.', 'Drip-feed delivery available.', 'No password or login required.', 'Works on any public handle.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['X regularly purges inactive accounts.', 'Profile must be public during delivery.', 'Drops are expected over time.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 24 h' },
    { i: 113, s: 'smm', b: 'twitter', n: 'X Post Views', k: 'SERVICE', dur: 'Per 1000', p: 0.12, int: 'smm',
      smm: { unit: 'views', min: 1000, max: 500000, step: 1000, rate: 0.12, field: 'Post link', ph: 'x.com/you/status/...' },
      d: ['Views added to a single post.', 'Starts within the hour.'], sp: { Unit: 'Per 1000' }, del: 'Under 3 h' },
    { i: 29, s: 'smm', b: 'twitch', n: 'Twitch Followers', k: 'SERVICE', dur: 'Per 1000', p: 0.85, int: 'smm',
      smm: { unit: 'followers', min: 100, max: 20000, step: 100, rate: 0.85, field: 'Twitch channel', ph: 'twitch.tv/yourchannel' },
      D: ['Followers added to your channel.', 'Delivered gradually to look organic.', 'No stream key or login required.', 'Helps reach affiliate requirements faster.', 'Delivered after payment confirmation.', 'Open a ticket if something does not work.'],
      W: ['Twitch may remove bot followers during audits.', 'Does not count toward affiliate viewer requirements.', 'Channel must be public.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 24 h' },
    { i: 114, s: 'smm', b: 'twitch', n: 'Twitch Live Viewers', k: 'SERVICE', dur: 'Per 100 / h', p: 1.90, int: 'smm',
      smm: { unit: 'viewers', min: 10, max: 1000, step: 10, rate: 19.0, field: 'Twitch channel', ph: 'twitch.tv/yourchannel' },
      d: ['Concurrent viewers held while you stream.', 'Started manually at the time you give in the ticket.'],
      w2: ['Viewbotting is against Twitch terms and gets channels suspended.', 'Chat stays empty, the audience is not real.'],
      sp: { Unit: 'Per 100 viewers / hour' }, del: 'Scheduled' },
    { i: 115, s: 'smm', b: 'kick', n: 'Kick Followers', k: 'SERVICE', dur: 'Per 1000', p: 0.75, int: 'smm',
      smm: { unit: 'followers', min: 100, max: 20000, step: 100, rate: 0.75, field: 'Kick channel', ph: 'kick.com/yourchannel' },
      d: ['Followers added to a public Kick channel.', 'Delivered gradually.'], sp: { Unit: 'Per 1000' }, del: 'Under 24 h' },
    { i: 116, s: 'smm', b: 'spotify', n: 'Spotify Plays', k: 'SERVICE', dur: 'Per 1000', p: 0.55, int: 'smm',
      smm: { unit: 'plays', min: 1000, max: 200000, step: 1000, rate: 0.55, field: 'Track link', ph: 'open.spotify.com/track/...' },
      d: ['Plays added to one track.', 'Delivered over several days to look natural.'],
      w2: ['Spotify filters artificial streams and can withhold royalties.'],
      sp: { Unit: 'Per 1000' }, del: 'Under 5 days' },
    { i: 117, s: 'smm', b: 'soundcloud', n: 'SoundCloud Plays', k: 'SERVICE', dur: 'Per 1000', p: 0.20, int: 'smm',
      smm: { unit: 'plays', min: 1000, max: 500000, step: 1000, rate: 0.20, field: 'Track link', ph: 'soundcloud.com/you/track' },
      d: ['Plays added to a public track.', 'Starts within a few hours.'], sp: { Unit: 'Per 1000' }, del: 'Under 6 h' },
    { i: 118, s: 'smm', b: 'facebook', n: 'Facebook Page Likes', k: 'SERVICE', dur: 'Per 1000', p: 1.10, int: 'smm',
      smm: { unit: 'likes', min: 100, max: 20000, step: 100, rate: 1.1, field: 'Page link', ph: 'facebook.com/yourpage' },
      d: ['Likes and follows added to a public page.', 'Delivered gradually.'], sp: { Unit: 'Per 1000' }, del: 'Under 24 h' }
  ];

  var PRODUCTS = RAW.map(mk);

  root.YSLEM = { shops: SHOPS, brands: BRANDS, products: PRODUCTS };

  if (typeof module !== 'undefined' && module.exports) module.exports = root.YSLEM;

})(typeof window !== 'undefined' ? window : globalThis);
